size_per_process: 512
upper_bound: 1
lower_bound: 0.1
coordinates_of_centers_in_r2:
  - [1, 1]
  - [2, 1.5]
  - [2, 1]
  - [3, 1.5]
respective_labels_of_clusters: [1, 1, -1, -1]
standard_deviation_of_clusters: 0.2
number_of_data_samples_per_cluster: 10
